# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/york-county" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

###
include: ["_pages"]

head_scripts:
  - https://code.jquery.com/jquery-3.3.1.min.js
  - https://unpkg.com/aos@next/dist/aos.js
  - https://d3js.org/d3.v6.min.js
  - https://unpkg.com/d3-sankey@0
  - https://d3js.org/d3-dsv.v1.min.js
  - https://vega.github.io/vega/vega.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/vega-lite/4.17.0/vega-lite.js
  - https://cdnjs.cloudflare.com/ajax/libs/vega-embed/6.12.2/vega-embed.js
#  - https://cdn.jsdelivr.net/npm/vega@5.17.0
#  - https://cdn.jsdelivr.net/npm/vega-lite@4.17.0
#  - https://cdn.jsdelivr.net/npm/vega-embed@6.12.2
  - /assets/js/test.js

collections:
  research:
    output: true
    permalink: /:collection/:path/
  project:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

###

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
